[project]
name = "rfsee"
version = "1.0.1"
description = "Visualize a chain of RFC documents"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.10"
dependencies = [
    "graphviz",
    "lxml",
    "click",
]

[project.urls]
Repository = "https://github.com/PandasAreBears/rfsee"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
rfsee = "rfsee.__main__:main"

[tool.setuptools.package-data]
rfsee = ["rfc-index.xml"]


